In [24]:
import pandas as pd
import os
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, StandardScaler,MinMaxScaler
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns

In [47]:
df=pd.read_csv('crop yield\yield_df.csv',index_col=0)

<>:1: SyntaxWarning: invalid escape sequence '\y'
<>:1: SyntaxWarning: invalid escape sequence '\y'
C:\Users\Krishna03\AppData\Local\Temp\ipykernel_7892\3476868530.py:1: SyntaxWarning: invalid escape sequence '\y'
  df=pd.read_csv('crop yield\yield_df.csv',index_col=0)


In [48]:
df

Area            Item  Year  hg/ha_yield  \
0       Albania           Maize  1990        36613   
1       Albania        Potatoes  1990        66667   
2       Albania     Rice, paddy  1990        23333   
3       Albania         Sorghum  1990        12500   
4       Albania        Soybeans  1990         7000   
...         ...             ...   ...          ...   
28237  Zimbabwe     Rice, paddy  2013        22581   
28238  Zimbabwe         Sorghum  2013         3066   
28239  Zimbabwe        Soybeans  2013        13142   
28240  Zimbabwe  Sweet potatoes  2013        22222   
28241  Zimbabwe           Wheat  2013        22888   

       average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  
0                               1485             121.00     16.37  
1                               1485             121.00     16.37  
2                               1485             121.00     16.37  
3                               1485             121.00     16.37  
4                               1485             121.00     16.37  
...                              ...                ...       ...  
28237                            657            2550.07     19.76  
28238                            657            2550.07     19.76  
28239                            657            2550.07     19.76  
28240                            657            2550.07     19.76  
28241                            657            2550.07     19.76  

[28242 rows x 7 columns]

In [50]:
x=df.drop(columns=['hg/ha_yield','Item','Area'])
y=df["hg/ha_yield"]

In [51]:
x

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp
0      1990                           1485             121.00     16.37
1      1990                           1485             121.00     16.37
2      1990                           1485             121.00     16.37
3      1990                           1485             121.00     16.37
4      1990                           1485             121.00     16.37
...     ...                            ...                ...       ...
28237  2013                            657            2550.07     19.76
28238  2013                            657            2550.07     19.76
28239  2013                            657            2550.07     19.76
28240  2013                            657            2550.07     19.76
28241  2013                            657            2550.07     19.76

[28242 rows x 4 columns]

In [52]:
y

0        36613
1        66667
2        23333
3        12500
4         7000
         ...  
28237    22581
28238     3066
28239    13142
28240    22222
28241    22888
Name: hg/ha_yield, Length: 28242, dtype: int64

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [54]:
x_train

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp
5493   2005                           1604             829.59     25.36
10969  1992                           1083           70791.00     25.91
2001   1997                           1292             484.59     25.81
22157  1997                            494           16936.00     23.76
311    2005                           1010              40.00     24.41
...     ...                            ...                ...       ...
21575  2001                            151              31.00     29.46
5390   1994                           1604             411.42     24.93
860    1991                            534           17866.00     18.73
15795  1996                            832           74617.20     12.28
23654  1999                            854           15411.00     16.09

[22593 rows x 4 columns]

In [55]:
y_train

5493      13173
10969      8947
2001      75317
22157    112295
311       46159
          ...  
21575     27565
5390      55053
860      285359
15795    221667
23654     88745
Name: hg/ha_yield, Length: 22593, dtype: int64

In [56]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [57]:
y_pred=model.predict(x_test)
y_pred

array([87437.64601715, 71512.70967045, 90603.0073555 , ...,
       63091.61754598, 93926.4525081 , 82530.61307763])

In [58]:
mse = mean_squared_error(y_test, y_pred)
mse




7050839404.175147

In [59]:
r2 = r2_score(y_test, y_pred)
r2

0.027962743215412367

In [60]:
mae=mean_absolute_error(y_test,y_pred)
mae

64079.40866247934

In [61]:
rmse=np.sqrt(mse)
rmse

83969.27654907566

In [62]:
from sklearn.linear_model import Ridge,Lasso

In [63]:
ridge_mod= Ridge(alpha=1.0)
ridge_score=cross_val_score(ridge_mod,x_train,y_train,cv=5)
ridge_score

array([0.02972459, 0.01932864, 0.02803767, 0.01493078, 0.02957812])

In [64]:
lasso_model=Lasso(alpha=1.0)
lasso_score=cross_val_score(lasso_model,x_train,y_train,cv=5)
lasso_score

array([0.02972444, 0.01932875, 0.02803764, 0.01493096, 0.02957805])

In [65]:
ridge_mod.fit(x_train,y_train)
ridge_pred=ridge_mod.predict(x_test)
ridge_pred

array([87437.63591981, 71512.71048688, 90602.99375256, ...,
       63091.63556688, 93926.43487187, 82530.62588678])

In [66]:
ridge_r=r2_score(y_test,ridge_pred)
ridge_r

0.027962739703884076

In [67]:
ridge_mse=mean_squared_error(y_test,ridge_pred)
ridge_mse

7050839429.646622

In [68]:
lasso_model.fit(x_train,y_train)
lasso_pred=lasso_model.predict(x_test)
lasso_pred

array([87437.46292828, 71512.75590544, 90602.76131825, ...,
       63091.91574836, 93926.21103835, 82530.79064562])

In [69]:
lasso_r2=r2_score(y_test,lasso_pred)
lasso_r2

0.027962702353232616